package com.flight.model;
// Generated Oct 27, 2017 3:14:11 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FlightCostsId generated by hbm2java
 */
@Embeddable
public class FlightCostsId implements java.io.Serializable {

	private int aircraftTypeCode;
	private int flightNumber;
	private String dayDate;

	public FlightCostsId() {
	}

	public FlightCostsId(int aircraftTypeCode, int flightNumber, String dayDate) {
		this.aircraftTypeCode = aircraftTypeCode;
		this.flightNumber = flightNumber;
		this.dayDate = dayDate;
	}

	@Column(name = "aircraft_type_code", nullable = false)
	public int getAircraftTypeCode() {
		return this.aircraftTypeCode;
	}

	public void setAircraftTypeCode(int aircraftTypeCode) {
		this.aircraftTypeCode = aircraftTypeCode;
	}

	@Column(name = "flight_number", nullable = false)
	public int getFlightNumber() {
		return this.flightNumber;
	}

	public void setFlightNumber(int flightNumber) {
		this.flightNumber = flightNumber;
	}

	@Column(name = "day_date", nullable = false, length = 50)
	public String getDayDate() {
		return this.dayDate;
	}

	public void setDayDate(String dayDate) {
		this.dayDate = dayDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FlightCostsId))
			return false;
		FlightCostsId castOther = (FlightCostsId) other;

		return (this.getAircraftTypeCode() == castOther.getAircraftTypeCode())
				&& (this.getFlightNumber() == castOther.getFlightNumber())
				&& ((this.getDayDate() == castOther.getDayDate()) || (this.getDayDate() != null
						&& castOther.getDayDate() != null && this.getDayDate().equals(castOther.getDayDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAircraftTypeCode();
		result = 37 * result + this.getFlightNumber();
		result = 37 * result + (getDayDate() == null ? 0 : this.getDayDate().hashCode());
		return result;
	}

}
