package com.flight.model;
// Generated Oct 27, 2017 3:14:11 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FlightSchedules generated by hbm2java
 */
@Entity
@Table(name = "flight_schedules")
public class FlightSchedules implements java.io.Serializable {

	private Integer flightNumber;
	private Airports airports;
	private Integer airlineCode;
	private String arrivalDateTime;
	private String departureDateTime;
	private Integer destinationAirportCode;
	private Integer usualAircraftTypeCode;
	private Set<FlightCosts> flightCostses = new HashSet<FlightCosts>(0);
	private Set<Legs> legses = new HashSet<Legs>(0);

	public FlightSchedules() {
	}

	public FlightSchedules(Airports airports, Integer airlineCode, String arrivalDateTime, String departureDateTime,
			Integer destinationAirportCode, Integer usualAircraftTypeCode, Set<FlightCosts> flightCostses,
			Set<Legs> legses) {
		this.airports = airports;
		this.airlineCode = airlineCode;
		this.arrivalDateTime = arrivalDateTime;
		this.departureDateTime = departureDateTime;
		this.destinationAirportCode = destinationAirportCode;
		this.usualAircraftTypeCode = usualAircraftTypeCode;
		this.flightCostses = flightCostses;
		this.legses = legses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "flight_number", unique = true, nullable = false)
	public Integer getFlightNumber() {
		return this.flightNumber;
	}

	public void setFlightNumber(Integer flightNumber) {
		this.flightNumber = flightNumber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "airport_code")
	public Airports getAirports() {
		return this.airports;
	}

	public void setAirports(Airports airports) {
		this.airports = airports;
	}

	@Column(name = "airline_code")
	public Integer getAirlineCode() {
		return this.airlineCode;
	}

	public void setAirlineCode(Integer airlineCode) {
		this.airlineCode = airlineCode;
	}

	@Column(name = "arrival_date_time", length = 50)
	public String getArrivalDateTime() {
		return this.arrivalDateTime;
	}

	public void setArrivalDateTime(String arrivalDateTime) {
		this.arrivalDateTime = arrivalDateTime;
	}

	@Column(name = "departure_date_time", length = 50)
	public String getDepartureDateTime() {
		return this.departureDateTime;
	}

	public void setDepartureDateTime(String departureDateTime) {
		this.departureDateTime = departureDateTime;
	}

	@Column(name = "destination_airport_code")
	public Integer getDestinationAirportCode() {
		return this.destinationAirportCode;
	}

	public void setDestinationAirportCode(Integer destinationAirportCode) {
		this.destinationAirportCode = destinationAirportCode;
	}

	@Column(name = "usual_aircraft_type_code")
	public Integer getUsualAircraftTypeCode() {
		return this.usualAircraftTypeCode;
	}

	public void setUsualAircraftTypeCode(Integer usualAircraftTypeCode) {
		this.usualAircraftTypeCode = usualAircraftTypeCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flightSchedules")
	public Set<FlightCosts> getFlightCostses() {
		return this.flightCostses;
	}

	public void setFlightCostses(Set<FlightCosts> flightCostses) {
		this.flightCostses = flightCostses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flightSchedules")
	public Set<Legs> getLegses() {
		return this.legses;
	}

	public void setLegses(Set<Legs> legses) {
		this.legses = legses;
	}

}
