package com.flight.model;
// Generated Oct 27, 2017 3:14:11 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Legs generated by hbm2java
 */
@Entity
@Table(name = "legs")
public class Legs implements java.io.Serializable {

	private Integer legId;
	private Airports airports;
	private FlightSchedules flightSchedules;
	private Integer destinationAirportCode;
	private String actualDepartureTime;
	private Set<ItineraryReservations> itineraryReservationses = new HashSet<ItineraryReservations>(0);

	public Legs() {
	}

	public Legs(Airports airports, FlightSchedules flightSchedules, Integer destinationAirportCode,
			String actualDepartureTime, Set<ItineraryReservations> itineraryReservationses) {
		this.airports = airports;
		this.flightSchedules = flightSchedules;
		this.destinationAirportCode = destinationAirportCode;
		this.actualDepartureTime = actualDepartureTime;
		this.itineraryReservationses = itineraryReservationses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "leg_id", unique = true, nullable = false)
	public Integer getLegId() {
		return this.legId;
	}

	public void setLegId(Integer legId) {
		this.legId = legId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "airport_code")
	public Airports getAirports() {
		return this.airports;
	}

	public void setAirports(Airports airports) {
		this.airports = airports;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "flight_number")
	public FlightSchedules getFlightSchedules() {
		return this.flightSchedules;
	}

	public void setFlightSchedules(FlightSchedules flightSchedules) {
		this.flightSchedules = flightSchedules;
	}

	@Column(name = "destination_airport_code")
	public Integer getDestinationAirportCode() {
		return this.destinationAirportCode;
	}

	public void setDestinationAirportCode(Integer destinationAirportCode) {
		this.destinationAirportCode = destinationAirportCode;
	}

	@Column(name = "actual_departure_time", length = 50)
	public String getActualDepartureTime() {
		return this.actualDepartureTime;
	}

	public void setActualDepartureTime(String actualDepartureTime) {
		this.actualDepartureTime = actualDepartureTime;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "itinerary_legs", catalog = "db_flight_booking", joinColumns = {
			@JoinColumn(name = "leg_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "reservation_id", nullable = false, updatable = false) })
	public Set<ItineraryReservations> getItineraryReservationses() {
		return this.itineraryReservationses;
	}

	public void setItineraryReservationses(Set<ItineraryReservations> itineraryReservationses) {
		this.itineraryReservationses = itineraryReservationses;
	}

}
