package com.flight.model;
// Generated Oct 27, 2017 3:14:11 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Passengers generated by hbm2java
 */
@Entity
@Table(name = "passengers")
public class Passengers implements java.io.Serializable {

	private Integer passengersId;
	private String addressLines;
	private String city;
	private String country;
	private String firstName;
	private String lastName;
	private String otherPassengerDetails;
	private String phoneNumber;
	private String secondName;
	private String stateProvinceCounty;
	private Set<ItineraryReservations> itineraryReservationses = new HashSet<ItineraryReservations>(0);

	public Passengers() {
	}

	public Passengers(String addressLines, String city, String country, String firstName, String lastName,
			String otherPassengerDetails, String phoneNumber, String secondName, String stateProvinceCounty,
			Set<ItineraryReservations> itineraryReservationses) {
		this.addressLines = addressLines;
		this.city = city;
		this.country = country;
		this.firstName = firstName;
		this.lastName = lastName;
		this.otherPassengerDetails = otherPassengerDetails;
		this.phoneNumber = phoneNumber;
		this.secondName = secondName;
		this.stateProvinceCounty = stateProvinceCounty;
		this.itineraryReservationses = itineraryReservationses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "passengers_id", unique = true, nullable = false)
	public Integer getPassengersId() {
		return this.passengersId;
	}

	public void setPassengersId(Integer passengersId) {
		this.passengersId = passengersId;
	}

	@Column(name = "address_lines", length = 30)
	public String getAddressLines() {
		return this.addressLines;
	}

	public void setAddressLines(String addressLines) {
		this.addressLines = addressLines;
	}

	@Column(name = "city", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country", length = 20)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "first_name", length = 20)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 20)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "other_passenger_details", length = 20)
	public String getOtherPassengerDetails() {
		return this.otherPassengerDetails;
	}

	public void setOtherPassengerDetails(String otherPassengerDetails) {
		this.otherPassengerDetails = otherPassengerDetails;
	}

	@Column(name = "phone_number", length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "second_name", length = 20)
	public String getSecondName() {
		return this.secondName;
	}

	public void setSecondName(String secondName) {
		this.secondName = secondName;
	}

	@Column(name = "state_province_county", length = 20)
	public String getStateProvinceCounty() {
		return this.stateProvinceCounty;
	}

	public void setStateProvinceCounty(String stateProvinceCounty) {
		this.stateProvinceCounty = stateProvinceCounty;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "passengers")
	public Set<ItineraryReservations> getItineraryReservationses() {
		return this.itineraryReservationses;
	}

	public void setItineraryReservationses(Set<ItineraryReservations> itineraryReservationses) {
		this.itineraryReservationses = itineraryReservationses;
	}

}
