package com.flight.model;
// Generated Oct 27, 2017 3:14:11 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Payments generated by hbm2java
 */
@Entity
@Table(name = "payments")
public class Payments implements java.io.Serializable {

	private Integer paymentId;
	private Integer paymentAmount;
	private String paymentDate;
	private String paymentStatusCode;
	private Set<ItineraryReservations> itineraryReservationses = new HashSet<ItineraryReservations>(0);

	public Payments() {
	}

	public Payments(Integer paymentAmount, String paymentDate, String paymentStatusCode,
			Set<ItineraryReservations> itineraryReservationses) {
		this.paymentAmount = paymentAmount;
		this.paymentDate = paymentDate;
		this.paymentStatusCode = paymentStatusCode;
		this.itineraryReservationses = itineraryReservationses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "payment_id", unique = true, nullable = false)
	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "payment_amount")
	public Integer getPaymentAmount() {
		return this.paymentAmount;
	}

	public void setPaymentAmount(Integer paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	@Column(name = "payment_date", length = 50)
	public String getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(String paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "payment_status_code", length = 20)
	public String getPaymentStatusCode() {
		return this.paymentStatusCode;
	}

	public void setPaymentStatusCode(String paymentStatusCode) {
		this.paymentStatusCode = paymentStatusCode;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "reservation_payments", catalog = "db_flight_booking", joinColumns = {
			@JoinColumn(name = "reservation_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "payment_id", nullable = false, updatable = false) })
	public Set<ItineraryReservations> getItineraryReservationses() {
		return this.itineraryReservationses;
	}

	public void setItineraryReservationses(Set<ItineraryReservations> itineraryReservationses) {
		this.itineraryReservationses = itineraryReservationses;
	}

}
