package com.flight.model;
// Generated Oct 27, 2017 3:14:11 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefCalendar generated by hbm2java
 */
@Entity
@Table(name = "ref_calendar")
public class RefCalendar implements java.io.Serializable {

	private String dayDate;
	private String businessDayYn;
	private Integer dayNumber;
	private Set<FlightCosts> flightCostses = new HashSet<FlightCosts>(0);

	public RefCalendar() {
	}

	public RefCalendar(String dayDate) {
		this.dayDate = dayDate;
	}

	public RefCalendar(String dayDate, String businessDayYn, Integer dayNumber, Set<FlightCosts> flightCostses) {
		this.dayDate = dayDate;
		this.businessDayYn = businessDayYn;
		this.dayNumber = dayNumber;
		this.flightCostses = flightCostses;
	}

	@Id

	@Column(name = "day_date", unique = true, nullable = false, length = 50)
	public String getDayDate() {
		return this.dayDate;
	}

	public void setDayDate(String dayDate) {
		this.dayDate = dayDate;
	}

	@Column(name = "business_day_yn", length = 50)
	public String getBusinessDayYn() {
		return this.businessDayYn;
	}

	public void setBusinessDayYn(String businessDayYn) {
		this.businessDayYn = businessDayYn;
	}

	@Column(name = "day_number")
	public Integer getDayNumber() {
		return this.dayNumber;
	}

	public void setDayNumber(Integer dayNumber) {
		this.dayNumber = dayNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refCalendar")
	public Set<FlightCosts> getFlightCostses() {
		return this.flightCostses;
	}

	public void setFlightCostses(Set<FlightCosts> flightCostses) {
		this.flightCostses = flightCostses;
	}

}
